<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VBNLNPQ" failures="1" tests="4" name="Test" time="0.351" errors="0" timestamp="2023-10-28T12:38:24 IST">
  <testcase classname="tests.RetryFailedTest" name="test2" time="0.045">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="tests.RetryFailedTest" name="test2" time="0.014">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="tests.RetryFailedTest" name="test2" time="0.005">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="tests.RetryFailedTest" name="test2" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.RetryFailedTest.test2(RetryFailedTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
